config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :new, :create, :show, :edit, :update]
  resources :product_models, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier

  validates :name, :weigth, :width, :height, :depth, :sku, presence: true
  validates :sku, uniqueness: true
  validates :weigth, :width, :height, :depth, numericality: { greater_than: 0 }
  validates :sku, format:  { with: /[A-Z0-9]{20}/ }
  validates :sku, length: { is: 20 }
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models
  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, :phone, presence: true
  validates :registration_number, uniqueness: true
  validates :registration_number, format: { with: /[0-9]{13}/ }
  validates :registration_number, length: { is: 13}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :description, :code, :address, :city, :cep, :area, presence: true
  validates :name, :code, uniqueness: true
  validates :cep, format: { with: /[0-9]{5}-[0-9]{3}/ }
  validates :code, length: { is: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
  end

  def create
    @product_model = ProductModel.new(product_model_params)

    if @product_model.save
      redirect_to product_models_path, notice: 'Cadastrado com sucesso'
    else
      flash.now[:notice] = 'Produto não cadastrado'
      render 'new'
    end
  end

  private
  def product_model_params
    params.require(:product_model).permit(:name, :weigth, :width, :height, :depth, :sku, :supplier_id)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only:[:show, :edit, :update]
  
  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to suppliers_path, notice: 'Cadastrado com sucesso'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado'
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_path, notice: 'Editado com sucesso'
    else
      flash.now[:notice] = 'Não foi possível atualizar o fornecedor'
      render 'edit'
    end
  end
  
  private
  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, :phone)
  end

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    
    if @warehouse.save
      redirect_to root_path, notice: 'Cadastrado com sucesso'
    else
      flash.now[:notice] = 'Galpão não cadastrado'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to warehouse_path(@warehouse), notice: 'Galpão atualizado com sucesso'
    else
      flash.now[:notice] = 'Não foi possível atualizar o galpão'
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to root_path, notice: 'Galpão removido com sucesso'
  end

  private
  def warehouse_params
    params.require(:warehouse).permit(:name, :description, :code, :address, :city, :cep, :area)
  end

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section id="warehouses">
  <h2>Galpões</h2>
  <div>
    <h3><%= link_to 'Cadastrar Galpão', new_warehouse_path %></h3>
  </div>
  <% @warehouses.each do |w| %>
   <div>
      <h3><%= link_to w.name, w %></h3>
      <dl>
        <dt>Código: </dt>
        <dd><%= w.code %></dd>
        <dt>Cidade: </dt>
        <dd><%= w.city %></dd>
        <dt>Área: </dt>
        <dd><%= w.area %>m²</dd>
      </dl>
    </div>
  <% end %>

  <% if @warehouses.empty? %>
    <p>Não há galpões cadastrados</p>
  <% end %>
</section>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse App - Campus Code</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1>Galpões & Estoque</h1>
      <nav>
        <%= link_to 'Fornecedores', suppliers_path %> | 
        <%= link_to 'Modelos de produtos', product_models_path %> |
        <% if user_signed_in? %>
          <%= current_user.email %>
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path %>
        <% end %>
      </nav> 
    </header>
    <main>
      <div>
        <%= alert %>
        <%= notice %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/product_models/_form.html.erb
<%= form_with(model: @product_model) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weigth %>
    <%= f.number_field :weigth%>
  </div>
  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>
    <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>
  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>
  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>
    <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, Supplier.order(:brand_name), :id, :brand_name %>
  </div>
  <div>
    <%= f.submit 'Cadastrar' %>
  </div>
<% end %>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>
<%= link_to 'Cadastrar novo modelo de produto', new_product_model_path %>

<% if @product_models.any?%>
  <% @product_models.each do |product| %>
    <div>
      <h2><%= product.name %></h2>
      <dl>
        <dt><strong>SKU:</strong></dt>
        <dd><%= product.sku %></dd>
        <dt><strong>Fornecedor</strong>:</dt>
        <dd><%= product.supplier.brand_name %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p>Não há modelo de produto cadastrado</p>
<% end %>

app/views/product_models/new.html.erb
<h1>Novo modelo de produto</h1>

<% if @product_model.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @product_model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f| %>
  <div>
    <%= f.label :corporate_name, 'Razão social' %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name, 'Nome fantasia' %>
    <%= f.text_field :brand_name%>
  </div>
  <div>
    <%= f.label :registration_number, 'CNPJ' %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :city, 'Cidade' %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state, 'Estado' %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :full_address, 'Endereço' %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :phone, 'Telefone' %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.submit 'Cadastrar' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<section id="edit_supplier">
  <h1>Editar Fornecedor</h1>

  <%= render 'form' %>
</section>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>
<h3><%= link_to 'Cadastrar Fornecedor', new_supplier_path %></h3>

<section id="suppliers">
  <% if @suppliers.any? %>
    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Local</th>
        </tr>
      </thead>
      <tbody>
        <% @suppliers.each do |supplier| %>
          <tr>
            <td><%= link_to supplier.brand_name, supplier %></td>
            <td><%= supplier.city %> - <%= supplier.state %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Não há fornecedores cadastrados</p>
  <% end %>
</section>
<%= link_to 'Voltar', root_path%>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>

<% if @supplier.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @supplier.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <%end%>
  </ul>
<% end %>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<section id="supplier">
  <h1>Fornecedor <%= @supplier.corporate_name %></h1>
  <%= link_to 'Editar', edit_supplier_path %>
  <div>
    <dl>
      <dt><strong>Documento: </strong></dt>
      <dd><%= @supplier.registration_number %></dd>
      <dt><strong>Endereço: </strong></dt>
      <dd><%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state%></dd>
      <dt><strong>Telefone: </strong></dt>
      <dd><%= @supplier.phone %></dd>
      <dt><strong>Email: </strong></dt>
      <dd><%= @supplier.email %></dd>
    </dl>
  </div>
</section>

<div>
  <%= link_to 'Voltar', suppliers_path %>
</div>

app/views/warehouses/_form.html.erb
<%= form_with(model: @warehouse) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>
  <div>
    <%= f.label :area %>
    <%= f.number_field :area %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<section id="edit_warehouse">
  <h1>Editar Galpão</h1>

  <%= render 'form' %>
</section>
<%= link_to 'Voltar', root_path %>

app/views/warehouses/new.html.erb
<h1>Novo Galpão</h1>

<% if(@warehouse.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @warehouse.errors.full_messages.each do |msg|%>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/warehouses/show.html.erb
<section id="warehouse">
  <h1>Galpão <%= @warehouse.code %></h1>
  <h2><%= @warehouse.description %></h2>

  <div>
    <dl>
      <dt><strong>Nome: </strong></dt>
      <dd><%= @warehouse.name %></dd>
      <dt><strong>Cidade: </strong></dt>
      <dd><%= @warehouse.city %></dd>
      <dt><strong>Área: </strong></dt>
      <dd><%= @warehouse.area %>m²</dd>
      <dt><strong>Endereço: </strong></dt>
      <dd><%= @warehouse.address %> <strong>CEP: </strong><%= @warehouse.cep %></dd></dd>
    </dl>
  </div>
</section>

<div>
  <%= link_to 'Editar', edit_warehouse_path(@warehouse) %>
  <%= link_to 'Voltar', root_path %>
</div>

<div>
  <%= button_to 'Excluir', warehouse_path(@warehouse), method: :delete %>
</div>